services:
  clinica-frontend:
    container_name: clinica_frontend_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production